###

GET http://localhost:3000/post

###

GET http://localhost:3000/post/62640ecc09ad88b729937fb9

###


GET http://localhost:3000/post?sender=dori

###

POST http://localhost:3000/post
Content-Type: application/json

{
  "message": "bye",
  "sender": "dori"
}

###

DELETE http://localhost:3000/post/62640ecc09ad88b729937fb9